const colors = {
  light: {
    text: "#1E293B",
    tint: "#2563EB",
    background: "#F0F4F8",
    foreground: "#1E293B",
    card: "#FFFFFF",
    cardForeground: "#1E293B",
    primary: "#2563EB",
    primaryForeground: "#FFFFFF",
    secondary: "#EFF6FF",
    secondaryForeground: "#2563EB",
    muted: "#F8FAFC",
    mutedForeground: "#64748B",
    textSecondary: "#64748B",
    accent: "#F0FDF4",
    accentForeground: "#15803D",
    destructive: "#DC2626",
    destructiveForeground: "#FFFFFF",
    border: "#E2E8F0",
    input: "#F1F5F9",
    success: "#16A34A",
    successBg: "#F0FDF4",
    warning: "#EA580C",
    warningBg: "#FFF7ED",
    danger: "#DC2626",
    dangerBg: "#FEF2F2",
    sale: "#16A34A",
    saleBg: "#DCFCE7",
    purchase: "#0284C7",
    purchaseBg: "#E0F2FE",
    expense: "#EA580C",
    expenseBg: "#FFF7ED",
    credit: "#7C3AED",
    creditBg: "#F3E8FF",
    surface: "#F8FAFC",
    surfaceElevated: "#FFFFFF",
    numpadKey: "#F1F5F9",
    numpadKeyText: "#1E293B",
    numpadAction: "#DBEAFE",
    numpadActionText: "#2563EB",
    numpadDelete: "#FEE2E2",
    numpadDeleteText: "#DC2626",
    overlay: "rgba(15,23,42,0.5)",
    headerBg: "#1E40AF",
    headerText: "#FFFFFF",
  },
  radius: 12,
};

export default colors;
