import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import locationsRouter from "./locations";
import accountsRouter from "./accounts";
import categoriesRouter from "./categories";
import productsRouter from "./products";
import customersRouter from "./customers";
import suppliersRouter from "./suppliers";
import salesRouter from "./sales";
import purchasesRouter from "./purchases";
import expensesRouter from "./expenses";
import creditsRouter from "./credits";
import walletsRouter from "./wallets";
import auditRouter from "./audit";
import dashboardRouter from "./dashboard";
import seedRouter from "./seed";
import currenciesRouter from "./currencies";
import cashCountsRouter from "./cash-counts";
import dollarWalletRouter from "./dollar-wallet";
import reportsRouter from "./reports.js";
import uploadRouter from "./upload.js";
import registrationsRouter from "./registrations.js";
import businessesRouter from "./businesses.js";
import hrmRouter from "./hrm.js";
import usdBridgeRouter from "./usd-bridge.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(locationsRouter);
router.use(accountsRouter);
router.use(categoriesRouter);
router.use(productsRouter);
router.use(customersRouter);
router.use(suppliersRouter);
router.use(salesRouter);
router.use(purchasesRouter);
router.use(expensesRouter);
router.use(creditsRouter);
router.use(walletsRouter);
router.use(auditRouter);
router.use(dashboardRouter);
router.use(seedRouter);
router.use(currenciesRouter);
router.use(cashCountsRouter);
router.use(dollarWalletRouter);
router.use(reportsRouter);
router.use(uploadRouter);
router.use(registrationsRouter);
router.use(businessesRouter);
router.use(hrmRouter);
router.use(usdBridgeRouter);

export default router;
